TRADING_DAYS_PER_YEAR = 252
DEFAULT_HISTORY_PERIOD = "3y"
MIN_HISTORY_DAYS = 60
DEFAULT_RANDOM_SEED = 42
DEFAULT_N_SIMS = 5000
DEFAULT_N_STEPS_PER_YEAR = 252
OUTPUT_DIR = "results"

# NEW
DEFAULT_RISK_FREE_RATE = 0.04
DEFAULT_BENCHMARK = "SPY"